// Sensor group settings generated by K-means clustering
// Generated: 2026-07-10T07:39:19.618Z
// Clusters: 15
// Regenerate with: node scripts/generate-sensor-groups.js

export interface SensorGroupSetting {
  name: string;
  keys: string[];
  jenksClass: number;
}

export interface Settings {
  sensorGroups: SensorGroupSetting[];
  generatedAt: string;
  numClasses: number;
}

export const SETTINGS: Settings = {
  "sensorGroups": [
    {
      "name": "Cluster 1",
      "keys": [
        "22",
        "23",
        "24",
        "34",
        "43",
        "52",
        "61",
        "70",
        "79",
        "115",
        "117",
        "119",
        "128",
        "132"
      ],
      "jenksClass": 0
    },
    {
      "name": "Cluster 2",
      "keys": [
        "121"
      ],
      "jenksClass": 1
    },
    {
      "name": "Cluster 3",
      "keys": [
        "131"
      ],
      "jenksClass": 2
    },
    {
      "name": "Cluster 4",
      "keys": [
        "124"
      ],
      "jenksClass": 3
    },
    {
      "name": "Cluster 5",
      "keys": [
        "127"
      ],
      "jenksClass": 4
    },
    {
      "name": "Cluster 6",
      "keys": [
        "130"
      ],
      "jenksClass": 5
    },
    {
      "name": "Cluster 7",
      "keys": [
        "123"
      ],
      "jenksClass": 6
    },
    {
      "name": "Cluster 8",
      "keys": [
        "116",
        "118",
        "120",
        "36",
        "45",
        "54",
        "88",
        "89",
        "125",
        "129"
      ],
      "jenksClass": 7
    },
    {
      "name": "Cluster 9",
      "keys": [
        "116"
      ],
      "jenksClass": 8
    },
    {
      "name": "Cluster 10",
      "keys": [
        "122"
      ],
      "jenksClass": 9
    },
    {
      "name": "Cluster 11",
      "keys": [
        "120"
      ],
      "jenksClass": 10
    },
    {
      "name": "Cluster 12",
      "keys": [
        "118"
      ],
      "jenksClass": 11
    },
    {
      "name": "Cluster 13",
      "keys": [
        "210"
      ],
      "jenksClass": 12
    },
    {
      "name": "Cluster 14",
      "keys": [
        "63",
        "72",
        "81"
      ],
      "jenksClass": 13
    },
    {
      "name": "Cluster 15",
      "keys": [
        "211"
      ],
      "jenksClass": 14
    }
  ],
  "generatedAt": "2026-07-10T07:39:19.618Z",
  "numClasses": 15
};

export function getSensorGroups(): SensorGroupSetting[] {
  return SETTINGS.sensorGroups;
}
